import { prisma } from "@/lib/prisma";
import type { DemoColonyData } from "@/lib/types";

function toIso(value?: Date | null) {
  return value ? value.toISOString() : undefined;
}

function asStringArray(value: unknown) {
  return Array.isArray(value) ? value.map((item) => String(item)) : [];
}

export async function getColonyDataSnapshot(): Promise<DemoColonyData> {
  const [
    users,
    facilities,
    rooms,
    racks,
    cages,
    strains,
    alleles,
    animals,
    animalAlleles,
    genotypingRecords,
    breedingSetups,
    breedingAdults,
    litters,
    litterAnimals,
    projects,
    projectAllocations,
    experiments,
    experimentAssignments,
    healthNotes,
    attachments,
    animalStatusEvents,
    animalMovements,
    cageMovements,
    ruleConfigs,
    alerts,
    auditLogs,
  ] = await prisma.$transaction([
    prisma.user.findMany(),
    prisma.facility.findMany(),
    prisma.room.findMany(),
    prisma.rack.findMany(),
    prisma.cage.findMany(),
    prisma.strain.findMany(),
    prisma.allele.findMany(),
    prisma.animal.findMany(),
    prisma.animalAllele.findMany(),
    prisma.genotypingRecord.findMany(),
    prisma.breedingSetup.findMany(),
    prisma.breedingAdult.findMany(),
    prisma.litter.findMany(),
    prisma.litterAnimal.findMany(),
    prisma.project.findMany(),
    prisma.animalProjectAllocation.findMany(),
    prisma.experiment.findMany(),
    prisma.experimentAssignment.findMany(),
    prisma.healthNote.findMany(),
    prisma.attachment.findMany(),
    prisma.animalStatusEvent.findMany(),
    prisma.animalMovement.findMany(),
    prisma.cageMovement.findMany(),
    prisma.ruleConfig.findMany(),
    prisma.alert.findMany(),
    prisma.auditLog.findMany(),
  ]);

  return {
    today: process.env.COLONY_REFERENCE_DATE ?? new Date().toISOString(),
    users: users.map((user) => ({
      id: user.id,
      name: user.name,
      email: user.email,
      password: "",
      role: user.role,
      active: user.active,
    })),
    facilities: facilities.map((facility) => ({
      id: facility.id,
      name: facility.name,
      notes: facility.notes ?? undefined,
    })),
    rooms: rooms.map((room) => ({
      id: room.id,
      facilityId: room.facilityId,
      roomNumber: room.roomNumber,
      notes: room.notes ?? undefined,
    })),
    racks: racks.map((rack) => ({
      id: rack.id,
      roomId: rack.roomId,
      rackNumber: rack.rackNumber,
      notes: rack.notes ?? undefined,
    })),
    cages: cages.map((cage) => ({
      id: cage.id,
      roomId: cage.roomId,
      rackId: cage.rackId,
      cageNumber: cage.cageNumber,
      barcode: cage.barcode,
      status: cage.status,
      notes: cage.notes ?? undefined,
      welfareFlags: asStringArray(cage.welfareFlags),
      lastUpdatedAt: cage.lastUpdatedAt.toISOString(),
    })),
    strains: strains.map((strain) => ({
      id: strain.id,
      name: strain.name,
      background: strain.background ?? "",
      notes: strain.notes ?? undefined,
      maintenanceRules: strain.maintenanceRules ? JSON.stringify(strain.maintenanceRules) : undefined,
    })),
    alleles: alleles.map((allele) => ({
      id: allele.id,
      name: allele.name,
      gene: allele.gene,
      type: allele.type,
      notes: allele.notes ?? undefined,
      harmfulHomozygous: allele.harmfulHomozygous,
      maintainAsHet: allele.maintainAsHet,
      prohibitedPairings: asStringArray(allele.prohibitedPairings),
    })),
    animals: animals.map((animal) => ({
      id: animal.id,
      animalId: animal.animalId,
      labId: animal.labId,
      sex: animal.sex,
      dob: animal.dob.toISOString(),
      strainId: animal.strainId,
      currentCageId: animal.currentCageId,
      status: animal.status,
      originType: animal.originType,
      sireId: animal.sireId ?? undefined,
      damId: animal.damId ?? undefined,
      breedingGeneration: animal.breedingGeneration ?? undefined,
      healthStatus: animal.healthStatus ?? "",
      projectSummary: animal.projectSummary ?? undefined,
      experimentalStatus: animal.experimentalStatus ?? "",
      outcomeStatus: animal.outcomeStatus,
      deathDate: toIso(animal.deathDate),
      deathReason: animal.deathReason ?? undefined,
      notes: animal.notes ?? undefined,
    })),
    animalAlleles,
    genotypingRecords: genotypingRecords.map((record) => ({
      id: record.id,
      animalId: record.animalId,
      sourceType: record.sourceType,
      assayType: record.assayType,
      sampleId: record.sampleId ?? undefined,
      markerTested: record.markerTested,
      resultText: record.resultText,
      attachmentUrl: record.attachmentUrl ?? undefined,
      sampleDate: record.sampleDate.toISOString(),
      resultDate: record.resultDate.toISOString(),
      operatorId: record.operatorId ?? undefined,
      provider: record.provider ?? undefined,
      verifiedById: record.verifiedById ?? undefined,
      finalCall: record.finalCall,
      status: record.status,
      confidence: record.confidence ?? undefined,
    })),
    breedingSetups: breedingSetups.map((setup) => ({
      id: setup.id,
      startDate: setup.startDate.toISOString(),
      endDate: toIso(setup.endDate),
      status: setup.status,
      targetGenotype: setup.targetGenotype,
      targetSex: setup.targetSex ?? undefined,
      notes: setup.notes ?? undefined,
    })),
    breedingAdults,
    litters: litters.map((litter) => ({
      id: litter.id,
      breedingSetupId: litter.breedingSetupId,
      birthDate: litter.birthDate.toISOString(),
      litterSizeBirth: litter.litterSizeBirth,
      litterSizeWean: litter.litterSizeWean ?? undefined,
      notes: litter.notes ?? undefined,
    })),
    litterAnimals,
    projects: projects.map((project) => ({
      id: project.id,
      projectCode: project.projectCode,
      title: project.title,
      ownerId: project.ownerId,
      notes: project.notes ?? undefined,
    })),
    projectAllocations: projectAllocations.map((allocation) => ({
      id: allocation.id,
      animalId: allocation.animalId,
      projectId: allocation.projectId,
      startedAt: allocation.startedAt.toISOString(),
      endedAt: toIso(allocation.endedAt),
      chargeable: allocation.chargeable,
      notes: allocation.notes ?? undefined,
    })),
    experiments: experiments.map((experiment) => ({
      id: experiment.id,
      experimentCode: experiment.experimentCode,
      projectId: experiment.projectId,
      title: experiment.title,
      ownerId: experiment.ownerId,
      status: experiment.status,
      notes: experiment.notes ?? undefined,
    })),
    experimentAssignments: experimentAssignments.map((assignment) => ({
      id: assignment.id,
      animalId: assignment.animalId,
      experimentId: assignment.experimentId,
      status: assignment.status,
      startDate: assignment.startDate.toISOString(),
      endDate: toIso(assignment.endDate),
      treatmentGroup: assignment.treatmentGroup ?? undefined,
      notes: assignment.notes ?? undefined,
      isPrimary: assignment.isPrimary,
    })),
    healthNotes: healthNotes.map((note) => ({
      id: note.id,
      animalId: note.animalId ?? undefined,
      cageId: note.cageId ?? undefined,
      noteType: note.noteType,
      severity: note.severity,
      note: note.note,
      followupRequired: note.followupRequired,
      actionTaken: note.actionTaken ?? undefined,
      resolved: note.resolved,
      createdById: note.createdById,
      createdAt: note.createdAt.toISOString(),
    })),
    attachments: attachments.map((attachment) => ({
      id: attachment.id,
      animalId: attachment.animalId ?? undefined,
      cageId: attachment.cageId ?? undefined,
      healthNoteId: attachment.healthNoteId ?? undefined,
      genotypingRecordId: attachment.genotypingRecordId ?? undefined,
      label: attachment.label,
      fileName: attachment.fileName,
      fileType: attachment.fileType,
      storageUrl: attachment.storageUrl,
    })),
    animalStatusEvents: animalStatusEvents.map((event) => ({
      id: event.id,
      animalId: event.animalId,
      fromStatus: event.fromStatus ?? undefined,
      toStatus: event.toStatus,
      happenedAt: event.happenedAt.toISOString(),
      actorId: event.actorId ?? undefined,
      reason: event.reason ?? undefined,
    })),
    animalMovements: animalMovements.map((movement) => ({
      id: movement.id,
      animalId: movement.animalId,
      fromCageId: movement.fromCageId ?? undefined,
      toCageId: movement.toCageId ?? undefined,
      movedById: movement.movedById ?? undefined,
      movedAt: movement.movedAt.toISOString(),
      reason: movement.reason ?? undefined,
    })),
    cageMovements: cageMovements.map((movement) => ({
      id: movement.id,
      cageId: movement.cageId,
      fromLocation: movement.fromLocation,
      toLocation: movement.toLocation,
      movedById: movement.movedById ?? undefined,
      movedAt: movement.movedAt.toISOString(),
      reason: movement.reason ?? undefined,
    })),
    ruleConfigs: ruleConfigs.map((rule) => ({
      id: rule.id,
      key: rule.key,
      label: rule.label,
      category: rule.category,
      valueType: rule.valueType as "number" | "boolean" | "text" | "json",
      value: rule.value as number | boolean | string | string[],
      description: rule.description ?? "",
      criticalBlock: rule.criticalBlock,
    })),
    manualAlerts: alerts.map((alert) => ({
      id: alert.id,
      entityType: alert.entityType as "animal" | "cage" | "litter" | "experiment" | "project",
      entityId: alert.entityId,
      alertType: alert.alertType,
      severity: alert.severity,
      message: alert.message,
      status: alert.status,
      generatedAt: alert.generatedAt.toISOString(),
      resolvedAt: toIso(alert.resolvedAt),
      source: (alert.source as "rule" | "manual") ?? "manual",
    })),
    auditLogs: auditLogs.map((log) => ({
      id: log.id,
      actorId: log.actorId ?? undefined,
      entityType: log.entityType,
      entityId: log.entityId,
      action: log.action,
      previousValue: (log.previousValue as Record<string, unknown> | null) ?? undefined,
      newValue: (log.newValue as Record<string, unknown> | null) ?? undefined,
      timestamp: log.timestamp.toISOString(),
    })),
  };
}
