ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'it_head';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'facility_admin';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'cmu_staff';
ALTER TYPE "UserRole" ADD VALUE IF NOT EXISTS 'lab_user';

ALTER TABLE "User"
ADD COLUMN IF NOT EXISTS "authzVersion" INTEGER NOT NULL DEFAULT 1;
