import type { SeedColonyData } from "@/lib/types";
import { SEED_REFERENCE_DATE } from "@/lib/seed-metadata";

import { seededDevUsers } from "../src/lib/dev-accounts";

export const seedColonyData: SeedColonyData = {
  today: SEED_REFERENCE_DATE,
  users: seededDevUsers,
  facilities: [
    {
      id: "facility-tcd",
      name: "TCD Biomedical Research Facility",
      notes: "Managed cloud MVP dataset for colony maintenance workflows.",
    },
  ],
  rooms: [
    {
      id: "room-a101",
      facilityId: "facility-tcd",
      roomNumber: "A101",
      notes: "Breeding and colony holding.",
    },
    {
      id: "room-a102",
      facilityId: "facility-tcd",
      roomNumber: "A102",
      notes: "Experiment and quarantine spaces.",
    },
  ],
  racks: [
    { id: "rack-a101-1", roomId: "room-a101", rackNumber: "R1" },
    { id: "rack-a101-2", roomId: "room-a101", rackNumber: "R2" },
    { id: "rack-a102-1", roomId: "room-a102", rackNumber: "R1" },
  ],
  cages: [
    {
      id: "cage-a101-001",
      roomId: "room-a101",
      rackId: "rack-a101-1",
      cageNumber: "001",
      barcode: "CM-A101-001",
      status: "breeding",
      notes: "Primary CreER x reporter breeding pair.",
      welfareFlags: [],
      lastUpdatedAt: "2026-04-04T13:10:00.000Z",
    },
    {
      id: "cage-a101-002",
      roomId: "room-a101",
      rackId: "rack-a101-1",
      cageNumber: "002",
      barcode: "CM-A101-002",
      status: "active",
      notes: "Male weanlings held pending project allocation.",
      welfareFlags: ["overcapacity-watch"],
      lastUpdatedAt: "2026-04-05T08:15:00.000Z",
    },
    {
      id: "cage-a101-003",
      roomId: "room-a101",
      rackId: "rack-a101-2",
      cageNumber: "003",
      barcode: "CM-A101-003",
      status: "active",
      notes: "Female weanlings reserved for downstream imaging studies.",
      welfareFlags: [],
      lastUpdatedAt: "2026-04-05T08:20:00.000Z",
    },
    {
      id: "cage-a102-004",
      roomId: "room-a102",
      rackId: "rack-a102-1",
      cageNumber: "004",
      barcode: "CM-A102-004",
      status: "experiment",
      notes: "Tamoxifen induction cohort in active experiment.",
      welfareFlags: ["monitor-post-procedure"],
      lastUpdatedAt: "2026-04-05T07:55:00.000Z",
    },
    {
      id: "cage-a102-005",
      roomId: "room-a102",
      rackId: "rack-a102-1",
      cageNumber: "005",
      barcode: "CM-A102-005",
      status: "quarantine",
      notes: "Mixed-sex holding conflict created deliberately for alert testing.",
      welfareFlags: ["mixed-sex", "aggression-note"],
      lastUpdatedAt: "2026-04-04T17:30:00.000Z",
    },
  ],
  strains: [
    {
      id: "strain-creer",
      name: "Cx3cr1-CreER",
      background: "C57BL/6J",
      notes: "Maintain as heterozygous.",
      maintenanceRules: "Avoid homozygous breeders where possible.",
    },
    {
      id: "strain-tdt",
      name: "Rosa26-LSL-tdTomato",
      background: "C57BL/6J",
      notes: "Reporter line for imaging cohorts.",
    },
    {
      id: "strain-creer-tdt",
      name: "Cx3cr1-CreER x Rosa26-LSL-tdTomato",
      background: "Mixed C57BL/6J",
      notes: "Primary dual-transgenic study line.",
    },
    {
      id: "strain-cas9",
      name: "Tmem119-Cas9",
      background: "C57BL/6J",
      notes: "Used for pilot editing workflow.",
    },
    {
      id: "strain-wt",
      name: "C57BL/6J",
      background: "C57BL/6J",
      notes: "Wild-type holding line.",
    },
  ],
  alleles: [
    {
      id: "allele-creer",
      name: "CreER",
      gene: "Cx3cr1",
      type: "inducible transgene",
      notes: "Maintain as heterozygous only.",
      harmfulHomozygous: true,
      maintainAsHet: true,
      prohibitedPairings: ["CreER+/+ x CreER+/+"],
    },
    {
      id: "allele-tdt",
      name: "tdTomato",
      gene: "Rosa26-LSL-tdTomato",
      type: "reporter",
      notes: "Reporter allele for lineage tracing.",
    },
    {
      id: "allele-cas9",
      name: "Cas9",
      gene: "Tmem119",
      type: "transgene",
      notes: "Monitor fertility when combined with reporter.",
    },
    {
      id: "allele-tmem119-flox",
      name: "Tmem119-flox",
      gene: "Tmem119",
      type: "conditional",
      notes: "Used in future cohorts.",
      maintainAsHet: true,
    },
  ],
  animals: [
    {
      id: "animal-001",
      animalId: "CM-24001",
      labId: "MC-2025-001",
      sex: "male",
      dob: "2025-09-12T00:00:00.000Z",
      strainId: "strain-creer",
      currentCageId: "cage-a101-001",
      status: "breeding",
      originType: "internal breeding",
      breedingGeneration: "F3",
      healthStatus: "Fit breeder",
      projectSummary: "PRJ-MICRO-24",
      experimentalStatus: "Not assigned",
      outcomeStatus: "alive",
      notes: "Experienced sire with stable litter history.",
    },
    {
      id: "animal-002",
      animalId: "CM-24002",
      labId: "MC-2025-002",
      sex: "female",
      dob: "2025-10-03T00:00:00.000Z",
      strainId: "strain-tdt",
      currentCageId: "cage-a101-001",
      status: "breeding",
      originType: "internal breeding",
      breedingGeneration: "F2",
      healthStatus: "Pregnancy monitored",
      projectSummary: "PRJ-MICRO-24",
      experimentalStatus: "Not assigned",
      outcomeStatus: "alive",
      notes: "Dam for active litter LIT-2026-014.",
    },
    {
      id: "animal-003",
      animalId: "CM-26003",
      labId: "MC-2026-003",
      sex: "female",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-creer-tdt",
      currentCageId: "cage-a101-003",
      status: "reserved",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      projectSummary: "PRJ-MICRO-24",
      experimentalStatus: "Reserved for induction",
      outcomeStatus: "alive",
    },
    {
      id: "animal-004",
      animalId: "CM-26004",
      labId: "MC-2026-004",
      sex: "male",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-creer-tdt",
      currentCageId: "cage-a101-002",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      projectSummary: "PRJ-NEURO-07",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
    {
      id: "animal-005",
      animalId: "CM-26005",
      labId: "MC-2026-005",
      sex: "male",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-creer-tdt",
      currentCageId: "cage-a101-002",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Genotype pending",
      experimentalStatus: "Blocked pending genotype",
      outcomeStatus: "alive",
    },
    {
      id: "animal-006",
      animalId: "CM-25006",
      labId: "MC-2025-006",
      sex: "female",
      dob: "2025-12-20T00:00:00.000Z",
      strainId: "strain-cas9",
      currentCageId: "cage-a102-004",
      status: "in_experiment",
      originType: "external transfer",
      breedingGeneration: "F1",
      healthStatus: "Monitor after dosing",
      projectSummary: "PRJ-MICRO-24",
      experimentalStatus: "Active in Tamoxifen induction",
      outcomeStatus: "alive",
    },
    {
      id: "animal-007",
      animalId: "CM-25007",
      labId: "MC-2025-007",
      sex: "female",
      dob: "2025-12-20T00:00:00.000Z",
      strainId: "strain-cas9",
      currentCageId: "cage-a102-004",
      status: "reserved",
      originType: "external transfer",
      breedingGeneration: "F1",
      healthStatus: "Healthy",
      projectSummary: "PRJ-MICRO-24",
      experimentalStatus: "Reserved but not started",
      outcomeStatus: "alive",
    },
    {
      id: "animal-008",
      animalId: "CM-22008",
      labId: "MC-2024-008",
      sex: "male",
      dob: "2024-06-11T00:00:00.000Z",
      strainId: "strain-creer",
      currentCageId: "cage-a102-005",
      status: "breeding",
      originType: "legacy breeder",
      breedingGeneration: "F5",
      healthStatus: "Old breeder",
      projectSummary: "PRJ-NEURO-07",
      experimentalStatus: "Not assigned",
      outcomeStatus: "alive",
      notes: "Should be retired soon based on age threshold.",
    },
    {
      id: "animal-009",
      animalId: "CM-25009",
      labId: "MC-2025-009",
      sex: "female",
      dob: "2026-01-14T00:00:00.000Z",
      strainId: "strain-wt",
      currentCageId: "cage-a102-005",
      status: "colony_holding",
      originType: "internal breeding",
      breedingGeneration: "F2",
      healthStatus: "Monitor for grooming issue",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
    {
      id: "animal-010",
      animalId: "CM-25010",
      labId: "MC-2025-010",
      sex: "male",
      dob: "2025-11-11T00:00:00.000Z",
      strainId: "strain-wt",
      currentCageId: null,
      status: "archived",
      originType: "internal breeding",
      breedingGeneration: "F2",
      healthStatus: "Archived",
      experimentalStatus: "Completed",
      outcomeStatus: "euthanized",
      deathDate: "2026-03-10T00:00:00.000Z",
      deathReason: "Terminal tissue collection",
      notes: "Retained for audit trail and tissue provenance.",
    },
    {
      id: "animal-011",
      animalId: "CM-26011",
      labId: "MC-2026-011",
      sex: "male",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-tdt",
      currentCageId: "cage-a101-002",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
    {
      id: "animal-012",
      animalId: "CM-26012",
      labId: "MC-2026-012",
      sex: "male",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-tdt",
      currentCageId: "cage-a101-002",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
    {
      id: "animal-013",
      animalId: "CM-26013",
      labId: "MC-2026-013",
      sex: "male",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-tdt",
      currentCageId: "cage-a101-002",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
    {
      id: "animal-014",
      animalId: "CM-26014",
      labId: "MC-2026-014",
      sex: "female",
      dob: "2026-03-01T00:00:00.000Z",
      strainId: "strain-tdt",
      currentCageId: "cage-a101-003",
      status: "colony_holding",
      originType: "litter LIT-2026-014",
      sireId: "animal-001",
      damId: "animal-002",
      breedingGeneration: "F4",
      healthStatus: "Healthy",
      experimentalStatus: "Available",
      outcomeStatus: "alive",
    },
  ],
  animalAlleles: [
    { id: "animal-allele-001", animalId: "animal-001", alleleId: "allele-creer", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-002", animalId: "animal-001", alleleId: "allele-tdt", zygosity: "WT/WT", callStatus: "confirmed" },
    { id: "animal-allele-003", animalId: "animal-002", alleleId: "allele-creer", zygosity: "WT/WT", callStatus: "confirmed" },
    { id: "animal-allele-004", animalId: "animal-002", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-005", animalId: "animal-003", alleleId: "allele-creer", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-006", animalId: "animal-003", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-007", animalId: "animal-004", alleleId: "allele-creer", zygosity: "WT/WT", callStatus: "confirmed" },
    { id: "animal-allele-008", animalId: "animal-004", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-009", animalId: "animal-005", alleleId: "allele-creer", zygosity: "+/-", callStatus: "pending" },
    { id: "animal-allele-010", animalId: "animal-005", alleleId: "allele-tdt", zygosity: "pending", callStatus: "pending" },
    { id: "animal-allele-011", animalId: "animal-006", alleleId: "allele-cas9", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-012", animalId: "animal-007", alleleId: "allele-cas9", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-013", animalId: "animal-008", alleleId: "allele-creer", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-014", animalId: "animal-011", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-015", animalId: "animal-012", alleleId: "allele-tdt", zygosity: "WT/WT", callStatus: "confirmed" },
    { id: "animal-allele-016", animalId: "animal-013", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
    { id: "animal-allele-017", animalId: "animal-014", alleleId: "allele-tdt", zygosity: "+/-", callStatus: "confirmed" },
  ],
  genotypingRecords: [
    {
      id: "geno-001",
      animalId: "animal-003",
      sourceType: "manual PCR",
      assayType: "gel PCR",
      sampleId: "PCR-003",
      markerTested: "CreER / tdTomato",
      resultText: "Expected bands present",
      sampleDate: "2026-03-15T00:00:00.000Z",
      resultDate: "2026-03-16T00:00:00.000Z",
      operatorId: "user-staff",
      verifiedById: "user-manager",
      finalCall: "Cre+/- ; tdTomato+/-",
      status: "confirmed",
      confidence: "high",
    },
    {
      id: "geno-002",
      animalId: "animal-004",
      sourceType: "manual PCR",
      assayType: "gel PCR",
      sampleId: "PCR-004",
      markerTested: "CreER / tdTomato",
      resultText: "Reporter positive, Cre absent",
      sampleDate: "2026-03-15T00:00:00.000Z",
      resultDate: "2026-03-16T00:00:00.000Z",
      operatorId: "user-staff",
      verifiedById: "user-manager",
      finalCall: "Cre WT/WT ; tdTomato+/-",
      status: "confirmed",
      confidence: "high",
    },
    {
      id: "geno-003",
      animalId: "animal-005",
      sourceType: "external vendor",
      assayType: "Transnetyx panel",
      sampleId: "TX-26005",
      markerTested: "CreER / tdTomato",
      resultText: "Awaiting vendor report upload",
      attachmentUrl: "/attachments/transnetyx-pending.pdf",
      sampleDate: "2026-03-12T00:00:00.000Z",
      resultDate: "2026-03-12T00:00:00.000Z",
      operatorId: "user-researcher",
      provider: "Transnetyx",
      finalCall: "Pending",
      status: "pending",
      confidence: "pending",
    },
    {
      id: "geno-004",
      animalId: "animal-006",
      sourceType: "manual PCR",
      assayType: "qPCR probe",
      sampleId: "QP-006",
      markerTested: "Cas9",
      resultText: "Positive amplification in expected window",
      sampleDate: "2026-01-10T00:00:00.000Z",
      resultDate: "2026-01-10T00:00:00.000Z",
      operatorId: "user-staff",
      verifiedById: "user-manager",
      finalCall: "Cas9+/-",
      status: "confirmed",
      confidence: "high",
    },
  ],
  breedingSetups: [
    {
      id: "breeding-001",
      startDate: "2026-01-12T00:00:00.000Z",
      status: "active",
      targetGenotype: "Cre+/- ; tdTomato+/-",
      targetSex: "female",
      notes: "Primary line maintenance cross for microglia imaging pipeline.",
    },
  ],
  breedingAdults: [
    { id: "breeding-adult-001", breedingSetupId: "breeding-001", animalId: "animal-001", role: "sire" },
    { id: "breeding-adult-002", breedingSetupId: "breeding-001", animalId: "animal-002", role: "dam" },
  ],
  litters: [
    {
      id: "litter-001",
      breedingSetupId: "breeding-001",
      birthDate: "2026-03-01T00:00:00.000Z",
      litterSizeBirth: 8,
      notes: "Large litter, weaning still incomplete in system.",
    },
  ],
  litterAnimals: [
    { id: "litter-animal-001", litterId: "litter-001", animalId: "animal-003" },
    { id: "litter-animal-002", litterId: "litter-001", animalId: "animal-004" },
    { id: "litter-animal-003", litterId: "litter-001", animalId: "animal-005" },
    { id: "litter-animal-004", litterId: "litter-001", animalId: "animal-011" },
    { id: "litter-animal-005", litterId: "litter-001", animalId: "animal-012" },
    { id: "litter-animal-006", litterId: "litter-001", animalId: "animal-013" },
    { id: "litter-animal-007", litterId: "litter-001", animalId: "animal-014" },
  ],
  projects: [
    {
      id: "project-micro",
      projectCode: "PRJ-MICRO-24",
      title: "Microglia lineage tracing",
      ownerId: "user-researcher",
      notes: "Primary imaging and induction project.",
    },
    {
      id: "project-neuro",
      projectCode: "PRJ-NEURO-07",
      title: "Neuroimmune response pilot",
      ownerId: "user-manager",
      notes: "Pilot cohort balancing and tissue collection.",
    },
  ],
  projectAllocations: [
    { id: "alloc-001", animalId: "animal-001", projectId: "project-micro", startedAt: "2025-09-20T00:00:00.000Z", chargeable: false },
    { id: "alloc-002", animalId: "animal-002", projectId: "project-micro", startedAt: "2025-10-12T00:00:00.000Z", chargeable: false },
    { id: "alloc-003", animalId: "animal-003", projectId: "project-micro", startedAt: "2026-03-25T00:00:00.000Z", chargeable: true },
    { id: "alloc-004", animalId: "animal-004", projectId: "project-neuro", startedAt: "2026-03-22T00:00:00.000Z", chargeable: true },
    { id: "alloc-008", animalId: "animal-004", projectId: "project-micro", startedAt: "2026-03-24T00:00:00.000Z", chargeable: false },
    { id: "alloc-005", animalId: "animal-006", projectId: "project-micro", startedAt: "2026-01-03T00:00:00.000Z", chargeable: true },
    { id: "alloc-006", animalId: "animal-007", projectId: "project-micro", startedAt: "2026-01-03T00:00:00.000Z", chargeable: true },
    { id: "alloc-007", animalId: "animal-008", projectId: "project-neuro", startedAt: "2024-06-18T00:00:00.000Z", chargeable: false },
  ],
  experiments: [
    {
      id: "experiment-001",
      experimentCode: "EXP-TAM-041",
      projectId: "project-micro",
      title: "Tamoxifen induction cohort",
      ownerId: "user-researcher",
      status: "active",
      notes: "Induction running with daily welfare monitoring.",
    },
    {
      id: "experiment-002",
      experimentCode: "EXP-LPS-005",
      projectId: "project-neuro",
      title: "LPS challenge pilot",
      ownerId: "user-manager",
      status: "planned",
      notes: "Balanced allocation pending genotype confirmation.",
    },
  ],
  experimentAssignments: [
    {
      id: "assign-001",
      animalId: "animal-006",
      experimentId: "experiment-001",
      status: "active",
      startDate: "2026-03-30T00:00:00.000Z",
      treatmentGroup: "Tamoxifen 75 mg/kg",
      notes: "Day 5 monitoring active.",
      isPrimary: true,
    },
    {
      id: "assign-002",
      animalId: "animal-007",
      experimentId: "experiment-002",
      status: "reserved",
      startDate: "2026-03-20T00:00:00.000Z",
      treatmentGroup: "LPS low dose",
      notes: "Reserved but study has not started.",
      isPrimary: true,
    },
    {
      id: "assign-003",
      animalId: "animal-003",
      experimentId: "experiment-001",
      status: "planned",
      startDate: "2026-04-10T00:00:00.000Z",
      treatmentGroup: "Tamoxifen backup",
      notes: "Hold for female Cre-positive reserve list.",
      isPrimary: false,
    },
  ],
  sampleRecords: [
    {
      id: "sample-001",
      animalId: "animal-004",
      projectId: "project-neuro",
      sampleLabel: "DNA-26004-A",
      sampleType: "Tail DNA",
      status: "stored",
      collectedAt: "2026-03-26T09:10:00.000Z",
      storageLocation: "Freezer 1 / Box A / A03",
      quantityLabel: "1 x 40 uL",
      notes: "Primary DNA aliquot retained for baseline cohort screening.",
      createdById: "user-manager",
      createdAt: "2026-03-26T09:30:00.000Z",
    },
    {
      id: "sample-002",
      animalId: "animal-006",
      projectId: "project-micro",
      sampleLabel: "SER-25006-01",
      sampleType: "Serum aliquot",
      status: "allocated",
      collectedAt: "2026-04-02T13:45:00.000Z",
      storageLocation: "Biobank / Rack 2 / B11",
      quantityLabel: "2 x 100 uL",
      notes: "Allocated to the cytokine response panel.",
      createdById: "user-researcher",
      createdAt: "2026-04-02T14:05:00.000Z",
    },
    {
      id: "sample-003",
      animalId: "animal-010",
      projectId: "project-neuro",
      sampleLabel: "BRAIN-25010-L",
      sampleType: "Brain hemisphere",
      status: "stored",
      collectedAt: "2026-03-10T10:00:00.000Z",
      storageLocation: "Cryobox 7 / C02",
      quantityLabel: "Left hemisphere",
      notes: "Terminal collection preserved for histology backfill.",
      createdById: "user-researcher",
      createdAt: "2026-03-10T10:30:00.000Z",
    },
  ],
  cryostorageRecords: [
    {
      id: "cryo-001",
      strainId: "strain-creer",
      projectId: "project-micro",
      sampleLabel: "CRYO-CREER-2026-01",
      materialType: "Frozen sperm",
      status: "stored",
      storedAt: "2026-02-18T10:00:00.000Z",
      storageLocation: "LN2 Tank A / Cane 3 / Goblet 2",
      quantityLabel: "6 straws",
      recoveryNotes: "Validated backup for heterozygous maintenance line.",
      notes: "Maintain as the primary disaster-recovery stock.",
      createdById: "user-manager",
      createdAt: "2026-02-18T10:20:00.000Z",
    },
    {
      id: "cryo-002",
      strainId: "strain-creer-tdt",
      projectId: "project-micro",
      sampleLabel: "CRYO-DUALTG-2026-02",
      materialType: "Two-cell embryos",
      status: "reserved",
      storedAt: "2026-03-05T14:30:00.000Z",
      storageLocation: "LN2 Tank B / Cane 1 / Goblet 4",
      quantityLabel: "18 embryos",
      recoveryNotes: "Reserved for recovery planning in Q3.",
      notes: "Use only if active colony productivity drops below target.",
      createdById: "user-admin",
      createdAt: "2026-03-05T15:00:00.000Z",
    },
    {
      id: "cryo-003",
      strainId: "strain-cas9",
      projectId: "project-neuro",
      sampleLabel: "CRYO-CAS9-2025-09",
      materialType: "Frozen sperm",
      status: "recovered",
      storedAt: "2025-09-20T09:15:00.000Z",
      storageLocation: "LN2 Tank A / Cane 5 / Goblet 1",
      quantityLabel: "Recovery complete",
      recoveryNotes: "Recovered successfully into live colony cohort in early 2026.",
      notes: "Retain record for lineage continuity and recovery history.",
      createdById: "user-manager",
      createdAt: "2025-09-20T09:45:00.000Z",
    },
  ],
  healthNotes: [
    {
      id: "health-001",
      cageId: "cage-a101-001",
      noteType: "pregnancy_suspicion",
      severity: "info",
      note: "Dam appeared pregnant before delivery. Resolved after litter confirmation.",
      followupRequired: false,
      actionTaken: "Litter logged and monitored.",
      resolved: true,
      createdById: "user-staff",
      createdAt: "2026-02-20T10:00:00.000Z",
    },
    {
      id: "health-002",
      animalId: "animal-006",
      noteType: "post_procedure_monitoring",
      severity: "warning",
      note: "Reduced activity 2 hours after tamoxifen dose.",
      followupRequired: true,
      actionTaken: "Repeat welfare check scheduled.",
      resolved: false,
      createdById: "user-staff",
      createdAt: "2026-04-04T15:30:00.000Z",
    },
    {
      id: "health-003",
      cageId: "cage-a102-005",
      noteType: "aggression",
      severity: "critical",
      note: "Fighting observed in quarantine cage with mixed-sex occupants.",
      followupRequired: true,
      actionTaken: "Escalate to colony manager for split decision.",
      resolved: false,
      createdById: "user-staff",
      createdAt: "2026-04-04T16:00:00.000Z",
    },
    {
      id: "health-004",
      animalId: "animal-009",
      noteType: "grooming_issue",
      severity: "warning",
      note: "Mild facial grooming issue observed during room check.",
      followupRequired: true,
      actionTaken: "Recheck tomorrow morning.",
      resolved: false,
      createdById: "user-staff",
      createdAt: "2026-04-05T08:10:00.000Z",
    },
  ],
  attachments: [
    {
      id: "attachment-001",
      genotypingRecordId: "geno-003",
      label: "Vendor placeholder report",
      fileName: "transnetyx-pending.pdf",
      fileType: "application/pdf",
      storageUrl: "/attachments/transnetyx-pending.pdf",
    },
    {
      id: "attachment-002",
      healthNoteId: "health-002",
      label: "Monitoring sheet",
      fileName: "monitoring-sheet-006.pdf",
      fileType: "application/pdf",
      storageUrl: "/attachments/monitoring-sheet-006.pdf",
    },
  ],
  animalStatusEvents: [
    {
      id: "status-001",
      animalId: "animal-003",
      fromStatus: "nursing",
      toStatus: "reserved",
      happenedAt: "2026-03-30T00:00:00.000Z",
      actorId: "user-manager",
      reason: "Reserved as backup female Cre-positive animal.",
    },
    {
      id: "status-002",
      animalId: "animal-006",
      fromStatus: "reserved",
      toStatus: "in_experiment",
      happenedAt: "2026-03-30T00:00:00.000Z",
      actorId: "user-researcher",
      reason: "Induction protocol started.",
    },
    {
      id: "status-003",
      animalId: "animal-010",
      fromStatus: "in_experiment",
      toStatus: "archived",
      happenedAt: "2026-03-10T00:00:00.000Z",
      actorId: "user-researcher",
      reason: "Terminal collection completed.",
    },
  ],
  animalMovements: [
    {
      id: "move-001",
      animalId: "animal-003",
      fromCageId: "cage-a101-001",
      toCageId: "cage-a101-003",
      movedById: "user-staff",
      movedAt: "2026-03-24T11:00:00.000Z",
      reason: "Weaning and sex split.",
    },
    {
      id: "move-002",
      animalId: "animal-004",
      fromCageId: "cage-a101-001",
      toCageId: "cage-a101-002",
      movedById: "user-staff",
      movedAt: "2026-03-24T11:00:00.000Z",
      reason: "Weaning and sex split.",
    },
  ],
  cageMovements: [
    {
      id: "cage-move-001",
      cageId: "cage-a102-004",
      fromLocation: "A102 / R1 / 003",
      toLocation: "A102 / R1 / 004",
      movedById: "user-manager",
      movedAt: "2026-03-28T09:30:00.000Z",
      reason: "Closer access for experiment monitoring.",
    },
  ],
  ruleConfigs: [
    {
      id: "rule-001",
      key: "breeder_min_age_days",
      label: "Breeder minimum age",
      category: "breeding",
      valueType: "number",
      value: 56,
      description: "Warn if a breeder is too young.",
      criticalBlock: true,
    },
    {
      id: "rule-002",
      key: "breeder_max_age_days",
      label: "Breeder maximum age",
      category: "breeding",
      valueType: "number",
      value: 270,
      description: "Warn if a breeder is beyond the preferred age window.",
      criticalBlock: false,
    },
    {
      id: "rule-003",
      key: "breeding_duration_max_days",
      label: "Maximum breeding duration",
      category: "breeding",
      valueType: "number",
      value: 180,
      description: "Warn if active breedings run too long.",
      criticalBlock: false,
    },
    {
      id: "rule-004",
      key: "weaning_due_days",
      label: "Weaning due age",
      category: "compliance",
      valueType: "number",
      value: 21,
      description: "Remind when litters reach the expected weaning age.",
      criticalBlock: false,
    },
    {
      id: "rule-005",
      key: "genotype_pending_days",
      label: "Pending genotype threshold",
      category: "genotype",
      valueType: "number",
      value: 14,
      description: "Warn if genotype confirmation is overdue.",
      criticalBlock: false,
    },
    {
      id: "rule-006",
      key: "cage_max_occupancy",
      label: "Maximum cage occupancy",
      category: "capacity",
      valueType: "number",
      value: 4,
      description: "Warn when cage occupancy exceeds facility preference.",
      criticalBlock: true,
    },
    {
      id: "rule-007",
      key: "mixed_sex_holding_allowed",
      label: "Allow mixed-sex holding",
      category: "capacity",
      valueType: "boolean",
      value: false,
      description: "If false, non-breeding cages with mixed sex raise alerts.",
      criticalBlock: true,
    },
    {
      id: "rule-008",
      key: "reservation_start_grace_days",
      label: "Reserved experiment grace period",
      category: "experiment",
      valueType: "number",
      value: 10,
      description: "Warn when reserved animals are not started promptly.",
      criticalBlock: false,
    },
    {
      id: "rule-009",
      key: "project_assignment_required_days",
      label: "Project assignment threshold",
      category: "compliance",
      valueType: "number",
      value: 84,
      description: "Warn when older holding animals still lack project allocation.",
      criticalBlock: false,
    },
    {
      id: "rule-010",
      key: "prohibited_cross_notes",
      label: "Prohibited cross notes",
      category: "breeding",
      valueType: "json",
      value: [
        "Do not breed homozygous Cre to homozygous flox.",
        "Maintain CreER line as heterozygous.",
      ],
      description: "Facility-specific breeding cautions.",
      criticalBlock: true,
    },
    {
      id: "rule-011",
      key: "notify_in_app_genotype_pending",
      label: "In-app overdue genotype notifications",
      category: "genotype",
      valueType: "boolean",
      value: true,
      description: "Show overdue genotype alerts in the notification inbox.",
      criticalBlock: false,
    },
    {
      id: "rule-012",
      key: "notify_in_app_weaning_due",
      label: "In-app weaning notifications",
      category: "compliance",
      valueType: "boolean",
      value: true,
      description: "Show overdue weaning alerts in the notification inbox.",
      criticalBlock: false,
    },
    {
      id: "rule-013",
      key: "notify_in_app_breeder_age",
      label: "In-app breeder age notifications",
      category: "breeding",
      valueType: "boolean",
      value: true,
      description: "Show breeder age alerts in the notification inbox.",
      criticalBlock: false,
    },
    {
      id: "rule-014",
      key: "notify_in_app_welfare",
      label: "In-app welfare notifications",
      category: "welfare",
      valueType: "boolean",
      value: true,
      description: "Show unresolved welfare and health-note alerts in the notification inbox.",
      criticalBlock: false,
    },
    {
      id: "rule-015",
      key: "notify_in_app_reservation_drift",
      label: "In-app reservation drift notifications",
      category: "experiment",
      valueType: "boolean",
      value: true,
      description: "Show reserved-but-not-started experiment alerts in the notification inbox.",
      criticalBlock: false,
    },
    {
      id: "rule-016",
      key: "notify_webhook_enabled",
      label: "Webhook notification delivery",
      category: "compliance",
      valueType: "boolean",
      value: false,
      description: "Allow admins or colony managers to POST notification digests to the configured webhook.",
      criticalBlock: false,
    },
    {
      id: "rule-017",
      key: "notify_webhook_url",
      label: "Notification webhook URL",
      category: "compliance",
      valueType: "text",
      value: "",
      description: "Destination URL for outbound notification webhook delivery.",
      criticalBlock: false,
    },
    {
      id: "rule-018",
      key: "notify_email_digest_recipients",
      label: "Notification digest recipients",
      category: "compliance",
      valueType: "text",
      value: "manager@colony.local; staff@colony.local",
      description: "Email-ready digest recipient list for external delivery tooling.",
      criticalBlock: false,
    },
    {
      id: "rule-019",
      key: "notify_email_enabled",
      label: "Email notification delivery",
      category: "compliance",
      valueType: "boolean",
      value: false,
      description: "POST notification digests to the configured HTTP email provider.",
      criticalBlock: false,
    },
    {
      id: "rule-020",
      key: "notify_email_provider_url",
      label: "Notification email provider URL",
      category: "compliance",
      valueType: "text",
      value: "",
      description: "HTTP mail-provider endpoint. The runtime sends from, to, subject, and text fields.",
      criticalBlock: false,
    },
    {
      id: "rule-021",
      key: "notify_email_from",
      label: "Notification email sender",
      category: "compliance",
      valueType: "text",
      value: "mouse-colony@colony.local",
      description: "From address used when email provider delivery is enabled.",
      criticalBlock: false,
    },
    {
      id: "rule-022",
      key: "sentinel_check_interval_days",
      label: "Sentinel check interval",
      category: "welfare",
      valueType: "number",
      value: 7,
      description: "Flag quarantine cages when sentinel or welfare checks are older than this interval.",
      criticalBlock: false,
    },
    {
      id: "rule-023",
      key: "quarantine_review_days",
      label: "Quarantine review threshold",
      category: "welfare",
      valueType: "number",
      value: 14,
      description: "Flag quarantine cages that need colony manager review after this many days.",
      criticalBlock: false,
    },
    {
      id: "rule-024",
      key: "breeding_fertility_target_litter_size",
      label: "Default target litter size",
      category: "breeding",
      valueType: "number",
      value: 6,
      description: "Fallback expected litter size when a breeder pair has no litter history.",
      criticalBlock: false,
    },
    {
      id: "rule-025",
      key: "breeding_fertility_high_average_pups",
      label: "Strong fertility average",
      category: "breeding",
      valueType: "number",
      value: 7,
      description: "Average litter size that earns the full fertility-history boost.",
      criticalBlock: false,
    },
    {
      id: "rule-026",
      key: "breeding_fertility_low_average_pups",
      label: "Weak fertility average",
      category: "breeding",
      valueType: "number",
      value: 5,
      description: "Average litter size below this value receives a fertility-history penalty.",
      criticalBlock: false,
    },
    {
      id: "rule-027",
      key: "breeding_fertility_history_boost_score",
      label: "Fertility history boost",
      category: "breeding",
      valueType: "number",
      value: 8,
      description: "Score bonus for breeders with strong litter-size history.",
      criticalBlock: false,
    },
    {
      id: "rule-028",
      key: "breeding_fertility_history_penalty_score",
      label: "Fertility history penalty",
      category: "breeding",
      valueType: "number",
      value: 8,
      description: "Score penalty for breeders with weak litter-size history.",
      criticalBlock: false,
    },
    {
      id: "rule-029",
      key: "breeding_active_workload_penalty_score",
      label: "Active breeder workload penalty",
      category: "breeding",
      valueType: "number",
      value: 8,
      description: "Score penalty applied per active breeding workload on either proposed parent.",
      criticalBlock: false,
    },
    {
      id: "rule-030",
      key: "breeding_surplus_penalty_per_pup",
      label: "Surplus penalty per pup",
      category: "breeding",
      valueType: "number",
      value: 2,
      description: "Score penalty applied per projected non-target pup in breeding helper suggestions.",
      criticalBlock: false,
    },
    {
      id: "rule-031",
      key: "breeding_surplus_warning_pups",
      label: "Surplus warning threshold",
      category: "breeding",
      valueType: "number",
      value: 4,
      description: "Warn when a suggested cross may produce at least this many non-target pups.",
      criticalBlock: false,
    },
    {
      id: "rule-032",
      key: "breeding_strain_fertility_profiles",
      label: "Line-specific fertility profiles",
      category: "breeding",
      valueType: "json",
      value: [
        {
          strainId: "strain-creer",
          label: "Cx3cr1-CreER maintenance",
          litterSizeMultiplier: 0.95,
          probabilityMultiplier: 1,
          surplusPenaltyMultiplier: 1.05,
          note: "Maintain the CreER line conservatively and review surplus before scaling cohorts.",
        },
        {
          strainId: "strain-tdt",
          label: "Rosa26 reporter",
          litterSizeMultiplier: 1.05,
          probabilityMultiplier: 1,
          surplusPenaltyMultiplier: 1,
          note: "Reporter line historically supports average litter sizes in this colony.",
        },
        {
          strainId: "strain-creer-tdt",
          label: "Dual-transgenic CreER reporter",
          litterSizeMultiplier: 0.9,
          probabilityMultiplier: 0.95,
          surplusPenaltyMultiplier: 1.15,
          note: "Dual-transgenic breeders should keep avoidable surplus visible during cohort planning.",
        },
        {
          strainId: "strain-cas9",
          label: "Tmem119-Cas9",
          litterSizeMultiplier: 0.85,
          probabilityMultiplier: 0.9,
          surplusPenaltyMultiplier: 1.2,
          note: "Monitor Cas9 fertility before relying on this line for high-yield cohorts.",
        },
      ],
      description: "Optional per-strain fertility multipliers used by breeding suggestions and supply forecasts.",
      criticalBlock: false,
    },
    {
      id: "rule-033",
      key: "forecast_long_range_horizon_days",
      label: "Long-range forecast horizon",
      category: "breeding",
      valueType: "number",
      value: 90,
      description: "Runway horizon for study-demand forecasting beyond the short 45-day planner.",
      criticalBlock: false,
    },
  ],
  manualAlerts: [
    {
      id: "manual-alert-001",
      entityType: "animal",
      entityId: "animal-006",
      alertType: "welfare_followup",
      severity: "warning",
      message: "Post-procedure monitoring follow-up still unresolved.",
      status: "open",
      generatedAt: "2026-04-04T15:35:00.000Z",
      source: "manual",
    },
  ],
  auditLogs: [
    {
      id: "audit-001",
      actorId: "user-manager",
      entityType: "breeding_setup",
      entityId: "breeding-001",
      action: "activate",
      previousValue: { status: "planned" },
      newValue: { status: "active" },
      timestamp: "2026-01-12T09:00:00.000Z",
    },
    {
      id: "audit-002",
      actorId: "user-staff",
      entityType: "animal",
      entityId: "animal-003",
      action: "move",
      previousValue: { currentCageId: "cage-a101-001" },
      newValue: { currentCageId: "cage-a101-003" },
      timestamp: "2026-03-24T11:00:00.000Z",
    },
    {
      id: "audit-003",
      actorId: "user-researcher",
      entityType: "experiment_assignment",
      entityId: "assign-001",
      action: "start",
      previousValue: { status: "reserved" },
      newValue: { status: "active" },
      timestamp: "2026-03-30T08:00:00.000Z",
    },
  ],
};
