"use client";

import { useActionState, type ReactNode } from "react";
import { useFormStatus } from "react-dom";

import {
  advanceCensusSessionAction,
  cancelTransferDispatchAction,
  confirmShipmentReceiptAction,
  createShipmentManifestAction,
  decideShipmentHealthCompatibilityAction,
  dispatchTransferCustodyAction,
  grantCapacityExceptionAction,
  recordCensusObservationAction,
  recordShipmentHealthEvidenceAction,
  recordShipmentObservationAction,
  receiveTransferCustodyAction,
  resolveCensusDiscrepancyAction,
  resolveTransferCustodyReconciliationAction,
  revokeCapacityExceptionAction,
  startCensusSessionAction,
  startShipmentReceiptAction,
} from "@/app/reconciliation/actions";
import { initialFormActionState, type FormActionState } from "@/lib/form-state";

type Action = (state: FormActionState, formData: FormData) => Promise<FormActionState>;
type Option = { id: string; label: string };

function Submit({ children }: { children: ReactNode }) {
  const { pending } = useFormStatus();
  return <button className="min-h-11 rounded-md bg-[var(--foreground)] px-4 py-2 text-sm font-semibold text-white disabled:opacity-50" disabled={pending} type="submit">{pending ? "Saving…" : children}</button>;
}

function ActionForm({ action, commandKey, children, submit }: { action: Action; commandKey: string; children: ReactNode; submit: string }) {
  const [state, formAction] = useActionState(action, initialFormActionState);
  return <form action={formAction} className="space-y-3 rounded-lg border border-[var(--line)] bg-white p-4">
    <input name="idempotencyKey" type="hidden" value={commandKey} /><input name="requestId" type="hidden" value={commandKey} />
    {children}
    {state.message ? <p className={state.status === "error" ? "text-sm text-red-700" : "text-sm text-emerald-700"} role="status">{state.message}</p> : null}
    <Submit>{submit}</Submit>
  </form>;
}

function Select({ name, label, options, required = true }: { name: string; label: string; options: Option[]; required?: boolean }) {
  return <label className="block space-y-1 text-sm"><span className="text-[var(--muted)]">{label}</span><select className="min-h-11 w-full rounded-md border border-[var(--line)] bg-white px-3" name={name} required={required}><option value="">Choose…</option>{options.map((option) => <option key={option.id} value={option.id}>{option.label}</option>)}</select></label>;
}

function Input({ name, label, type = "text", defaultValue, required = true }: { name: string; label: string; type?: string; defaultValue?: string | number; required?: boolean }) {
  return <label className="block space-y-1 text-sm"><span className="text-[var(--muted)]">{label}</span><input className="min-h-11 w-full rounded-md border border-[var(--line)] px-3" defaultValue={defaultValue} name={name} required={required} type={type} /></label>;
}

type Workspace = {
  permissions: { canManage: boolean; canApprove: boolean; canRelease: boolean };
  manifests: Array<{ id: string; labId: string; externalReference: string; sourceName: string; status: string; healthEvidenceStatus: string; version: number; items: Array<{ id: string; expectedIdentifier: string; expectedSex: string; expectedDob: string; status: string }>; sessions: Array<{ id: string; status: string; version: number }>; observations: Array<{ id: string; outcome: string; observedIdentifier: string }>; healthEvidence: Array<{ id: string; testCode: string; result: string }>; healthDecisions: Array<{ id: string; decision: string; evidenceCount: number }>; reconciliation: null | { result: string; acceptedCount: number; exceptionCount: number; missingCount: number } }>;
  censusSessions: Array<{ id: string; labId: string; status: string; version: number; observations: Array<{ id: string; outcome: string; observedIdentifier: string }> }>;
  discrepancies: Array<{ id: string; sessionId: string; status: string; discrepancyType: string; version: number; ownerId: string; resolvedById: string | null }>;
  capacityExceptions: Array<{ id: string; cageId: string; status: string; additionalCapacity: number; reason: string; expiresAt: string; current: boolean; version: number }>;
  custodyEvents: Array<{ id: string; requestId: string; eventType: string; expectedItemCount: number; observedItemCount: number; sourceLab: null | { code: string }; destinationLab: null | { code: string } }>;
  custodyReconciliations: Array<{ id: string; requestId: string; status: string; version: number; resolvedById: string | null }>;
  options: {
    activeLabId: string | null;
    unitScoped: boolean;
    labs: Array<{ id: string; name: string; code: string }>;
    strains: Array<{ id: string; name: string }>;
    protocols: Array<{ id: string; labId: string; protocolCode: string; title: string }>;
    cages: Array<{ id: string; labId: string; barcode: string }>;
    quarantineCages: Array<{ id: string; labId: string; barcode: string }>;
    rooms: Array<{ id: string; roomNumber: string }>;
    owners: Array<{ id: string; name: string }>;
    transfers: Array<{ id: string; sourceLabId: string; destinationLabId: string; status: string; version: number; reason: string; items: Array<{ animalId: string; animal: { facilityAnimalId: string } }> }>;
  };
};

export function ReconciliationWorkbench({ workspace, nonce, today }: { workspace: Workspace; nonce: string; today: string }) {
  const label = (items: Array<{ id: string; [key: string]: unknown }>, key: string) => items.map((item) => ({ id: item.id, label: String(item[key]) }));
  const labs = workspace.options.labs.map((lab) => ({ id: lab.id, label: `${lab.code} · ${lab.name}` }));
  const strains = label(workspace.options.strains, "name");
  const owners = label(workspace.options.owners, "name");
  const rooms = label(workspace.options.rooms, "roomNumber");
  const cages = label(workspace.options.cages, "barcode");
  const quarantineCages = label(workspace.options.quarantineCages, "barcode");
  return <div className="space-y-6" data-testid="reconciliation-workbench">
    <div className="rounded-lg border border-amber-300 bg-amber-50 p-4 text-sm text-amber-950"><strong>Synthetic fail-closed boundary.</strong> This is controlled operational reconciliation, not an automatic correction tool. It never silently rewrites animals, cages, ownership, or retained history. Purchased receipt requires a pre-existing empty quarantine cage.</div>
    {workspace.permissions.canManage ? <section className="space-y-3"><h2 className="text-lg font-semibold">Expected shipment</h2><ActionForm action={createShipmentManifestAction} commandKey={`${nonce}:manifest`} submit="Create expected manifest"><div className="grid gap-3 md:grid-cols-2"><Select name="labId" label="Receiving lab" options={labs} /><Input name="sourceName" label="Vendor/source" /><Input name="externalReference" label="Order/reference" /><Input name="expectedAt" label="Expected date" type="date" defaultValue={today} /><Select name="protocolAuthorizationId" label="Protocol authorization" options={workspace.options.protocols.map((row) => ({ id: row.id, label: `${row.protocolCode} · ${row.title}` }))} /><Input name="expectedIdentifier" label="Source animal ID" /><Select name="strainId" label="Strain" options={strains} /><Select name="expectedSex" label="Expected sex" options={[{ id: "male", label: "Male" }, { id: "female", label: "Female" }]} /><Input name="expectedDob" label="Expected date of birth" type="date" defaultValue={today} /></div></ActionForm></section> : null}

    <section className="space-y-3"><h2 className="text-lg font-semibold">Shipment receiving queue</h2>{workspace.manifests.length ? <div className="grid gap-4 xl:grid-cols-2">{workspace.manifests.map((manifest) => { const open = manifest.sessions.find((session) => ["in_progress", "ready_for_confirmation"].includes(session.status)); const item = manifest.items.find((row) => row.status === "expected"); return <article className="space-y-3 rounded-lg border border-[var(--line)] bg-white p-4" key={manifest.id} data-testid={`manifest-${manifest.id}`}><div className="flex flex-wrap items-start justify-between gap-2"><div><strong>{manifest.externalReference}</strong><p className="text-sm text-[var(--muted)]">{manifest.sourceName} · {manifest.items.length} expected</p></div><span className="rounded-full border px-2 py-1 text-xs">{manifest.status.replaceAll("_", " ")} · health {manifest.healthEvidenceStatus}</span></div><p className="text-xs text-[var(--muted)]">Observed: {manifest.observations.map((row) => `${row.observedIdentifier} ${row.outcome}`).join(", ") || "none"}</p>{manifest.reconciliation ? <p className="text-sm font-medium">{manifest.reconciliation.result}: {manifest.reconciliation.acceptedCount} accepted, {manifest.reconciliation.exceptionCount} exception, {manifest.reconciliation.missingCount} missing</p> : null}
      {workspace.permissions.canManage && !["received", "cancelled"].includes(manifest.status) ? <div className="grid gap-3 md:grid-cols-2"><ActionForm action={recordShipmentHealthEvidenceAction} commandKey={`${nonce}:health:${manifest.id}:${manifest.version}`} submit="Record health evidence"><input name="manifestId" type="hidden" value={manifest.id} /><input name="expectedVersion" type="hidden" value={manifest.version} /><Select name="evidenceType" label="Evidence type" options={[{ id: "sentinel_panel", label: "Sentinel panel" }, { id: "vendor_certificate", label: "Vendor certificate" }]} /><Input name="testCode" label="Test/panel code" defaultValue="SYNTHETIC-PANEL" /><Select name="result" label="Result" options={[{ id: "negative", label: "Negative (awaits independent veterinary decision)" }, { id: "positive", label: "Positive / blocked" }, { id: "inconclusive", label: "Inconclusive" }, { id: "incompatible", label: "Incompatible" }]} /><Input name="collectedAt" label="Collected" type="date" defaultValue={today} /><Input name="issuedAt" label="Issued" type="datetime-local" defaultValue={`${today}T12:00`} /><Input name="issuer" label="Issuer" defaultValue="Synthetic QA laboratory" /><Input name="operationalSummary" label="Operational summary" defaultValue="Synthetic health evidence for local QA only." /></ActionForm>{manifest.status === "expected" ? <ActionForm action={startShipmentReceiptAction} commandKey={`${nonce}:start:${manifest.id}:${manifest.version}`} submit="Start receiving"><input name="manifestId" type="hidden" value={manifest.id} /><input name="expectedVersion" type="hidden" value={manifest.version} /><p className="text-sm text-[var(--muted)]">Receiving is resumable. Duplicate identifiers become explicit exceptions.</p></ActionForm> : null}</div> : null}
      {workspace.permissions.canRelease && !["received", "cancelled"].includes(manifest.status) && manifest.healthEvidence.length ? <ActionForm action={decideShipmentHealthCompatibilityAction} commandKey={`${nonce}:health-decision:${manifest.id}:${manifest.version}`} submit="Record independent veterinary decision"><input name="manifestId" type="hidden" value={manifest.id} /><input name="expectedVersion" type="hidden" value={manifest.version} /><Select name="decision" label="Veterinary decision" options={[{ id: "compatible", label: "Compatible — only if every current result is negative" }, { id: "blocked", label: "Blocked" }]} /><Input name="reason" label="Independent decision reason" defaultValue="Independent synthetic veterinary review of the complete append-only evidence set." /><p className="text-xs text-[var(--muted)]">You cannot certify evidence that you recorded. Any later positive, incompatible, or inconclusive evidence keeps intake blocked.</p></ActionForm> : null}
      {workspace.permissions.canManage && open && item ? <div className="grid gap-3 md:grid-cols-2"><ActionForm action={recordShipmentObservationAction} commandKey={`${nonce}:observe:${open.id}:${open.version}`} submit="Record receipt observation"><input name="sessionId" type="hidden" value={open.id} /><input name="expectedVersion" type="hidden" value={open.version} /><Select name="manifestItemId" label="Expected item" options={manifest.items.map((row) => ({ id: row.id, label: row.expectedIdentifier }))} required={false} /><Input name="observedIdentifier" label="Observed identifier" defaultValue={item.expectedIdentifier} /><Select name="outcome" label="Outcome" options={[{ id: "matched", label: "Matched" }, { id: "duplicate", label: "Duplicate" }, { id: "unknown", label: "Unknown" }, { id: "mismatched", label: "Mismatched" }, { id: "damaged", label: "Damaged label/shipment" }, { id: "dead_on_arrival", label: "Dead on arrival" }, { id: "rejected", label: "Rejected" }]} /><Select name="observedSex" label="Observed sex" options={[{ id: "male", label: "Male" }, { id: "female", label: "Female" }]} required={false} /><Input name="observedDob" label="Observed date of birth" type="date" defaultValue={item.expectedDob} required={false} /><Input name="operationalCondition" label="Exception details" required={false} /></ActionForm><ActionForm action={confirmShipmentReceiptAction} commandKey={`${nonce}:confirm:${open.id}:${open.version}`} submit="Confirm atomically"><input name="sessionId" type="hidden" value={open.id} /><input name="expectedVersion" type="hidden" value={open.version} /><Select name="destinationCageId" label="Pre-existing empty quarantine cage" options={quarantineCages} required={false} /><Input name="receivedAt" label="Received date" type="date" defaultValue={today} /><Input name="minimumHoldDays" label="Minimum hold days" type="number" defaultValue={14} /><p className="text-xs text-[var(--muted)]">If no items match, an exception-only reconciliation is recorded and no colony state changes.</p></ActionForm></div> : null}</article>; })}</div> : <p className="rounded-lg border border-dashed p-5 text-sm text-[var(--muted)]">No expected shipment manifests in your authorized scope.</p>}</section>

    {(workspace.permissions.canManage || workspace.permissions.canApprove) ? <section className="space-y-3">
      <h2 className="text-lg font-semibold">Census</h2>
      {workspace.permissions.canManage ? <ActionForm action={startCensusSessionAction} commandKey={`${nonce}:census-start`} submit="Start census"><div className="grid gap-3 md:grid-cols-2"><Select name="labId" label="Lab" options={labs} /><Select name="roomId" label="Room" options={rooms} /><Input name="rackLabel" label="Rack label (optional)" required={false} /><Select name="ownerId" label="Discrepancy owner" options={owners} /></div></ActionForm> : null}
      <div className="grid gap-4 xl:grid-cols-2">{workspace.censusSessions.map((session) => <article className="space-y-3 rounded-lg border border-[var(--line)] bg-white p-4" key={session.id}>
        <strong>Census {session.id.slice(-8)} · {session.status.replaceAll("_", " ")}</strong>
        <p className="text-sm text-[var(--muted)]">{session.observations.length} append-only observations</p>
        {workspace.permissions.canManage && session.status === "in_progress" ? <ActionForm action={recordCensusObservationAction} commandKey={`${nonce}:census-observe:${session.id}:${session.version}`} submit="Record census observation"><input name="sessionId" type="hidden" value={session.id} /><input name="expectedVersion" type="hidden" value={session.version} /><Select name="cageId" label="Known cage (leave blank for unknown)" options={cages} required={false} /><Input name="observedIdentifier" label="Observed barcode/identifier" /><Input name="observedLiveCount" label="Live count" type="number" required={false} /><Input name="observedMaleCount" label="Male count" type="number" required={false} /><Input name="observedFemaleCount" label="Female count" type="number" required={false} /><Select name="outcome" label="Outcome" options={[{ id: "matched", label: "Matched" }, { id: "count_mismatch", label: "Count mismatch" }, { id: "unknown", label: "Unknown cage" }, { id: "wrong_location", label: "Wrong location" }, { id: "damaged_label", label: "Damaged label" }, { id: "empty", label: "Unexpectedly empty" }]} /><Input name="operationalCondition" label="Discrepancy details" required={false} /></ActionForm> : null}
        {workspace.permissions.canManage && session.status === "in_progress" ? <ActionForm action={advanceCensusSessionAction} commandKey={`${nonce}:census-review:${session.id}:${session.version}`} submit="Submit for review"><input name="sessionId" type="hidden" value={session.id} /><input name="expectedVersion" type="hidden" value={session.version} /><input name="action" type="hidden" value="submit_review" /><p className="text-xs text-[var(--muted)]">No census action automatically changes colony truth.</p></ActionForm> : null}
        {workspace.permissions.canApprove && session.status === "review" ? <ActionForm action={advanceCensusSessionAction} commandKey={`${nonce}:census-signoff:${session.id}:${session.version}`} submit="Sign off census"><input name="sessionId" type="hidden" value={session.id} /><input name="expectedVersion" type="hidden" value={session.version} /><input name="action" type="hidden" value="sign_off" /><p className="text-xs text-[var(--muted)]">Every discrepancy must have independent sign-off first.</p></ActionForm> : null}
      </article>)}</div>
      <div className="grid gap-3 xl:grid-cols-2">{workspace.discrepancies.map((row) => <article className="space-y-2 rounded-lg border border-[var(--line)] bg-white p-4" key={row.id} data-testid="census-discrepancy"><strong>{row.discrepancyType.replaceAll("_", " ")} · {row.status.replaceAll("_", " ")}</strong>
        {workspace.permissions.canManage && ["open", "assigned"].includes(row.status) ? <ActionForm action={resolveCensusDiscrepancyAction} commandKey={`${nonce}:discrepancy-resolve:${row.id}:${row.version}`} submit="Resolve without rewriting"><input name="discrepancyId" type="hidden" value={row.id} /><input name="expectedVersion" type="hidden" value={row.version} /><input name="action" type="hidden" value="resolve" /><Input name="reason" label="Resolution evidence" defaultValue="Synthetic operational discrepancy reviewed." /></ActionForm> : null}
        {workspace.permissions.canApprove && row.status === "resolved" ? <ActionForm action={resolveCensusDiscrepancyAction} commandKey={`${nonce}:discrepancy-signoff:${row.id}:${row.version}`} submit="Independently sign off"><input name="discrepancyId" type="hidden" value={row.id} /><input name="expectedVersion" type="hidden" value={row.version} /><input name="action" type="hidden" value="sign_off" /><Input name="reason" label="Sign-off reason" defaultValue="Independent synthetic QA sign-off." /></ActionForm> : null}
      </article>)}</div>
    </section> : null}

    {workspace.permissions.canApprove ? <section className="space-y-3"><h2 className="text-lg font-semibold">Temporary capacity exception</h2><div className="rounded-md border border-sky-200 bg-sky-50 p-3 text-sm text-sky-950">An exception is time-limited operational evidence. It does not bypass the facility hard cage limit or automatically move animals.</div><ActionForm action={grantCapacityExceptionAction} commandKey={`${nonce}:capacity`} submit="Grant expiring exception"><div className="grid gap-3 md:grid-cols-2"><Select name="cageId" label="Cage" options={cages} /><Input name="additionalCapacity" label="Additional spaces" type="number" defaultValue={1} /><Input name="startsAt" label="Starts" type="datetime-local" defaultValue={`${today}T08:00`} /><Input name="expiresAt" label="Expires (max 30 days)" type="datetime-local" defaultValue={`${today}T20:00`} /><Input name="reason" label="Reason" defaultValue="Synthetic temporary operational exception." /></div></ActionForm><div className="grid gap-3 md:grid-cols-2">{workspace.capacityExceptions.map((row) => <article className="space-y-2 rounded-lg border border-[var(--line)] bg-white p-4" key={row.id}><strong>{row.current ? "Current" : row.status === "active" ? "Expired by time" : row.status} · +{row.additionalCapacity}</strong><p className="text-sm text-[var(--muted)]">{row.reason} · expires {new Date(row.expiresAt).toLocaleString()}</p>{row.status === "active" && row.current ? <ActionForm action={revokeCapacityExceptionAction} commandKey={`${nonce}:capacity-revoke:${row.id}:${row.version}`} submit="Revoke exception"><input name="exceptionId" type="hidden" value={row.id} /><input name="expectedVersion" type="hidden" value={row.version} /><Input name="reason" label="Revocation reason" defaultValue="Synthetic exception no longer required." /></ActionForm> : null}</article>)}</div></section> : null}

    {workspace.permissions.canManage ? <section className="space-y-3"><h2 className="text-lg font-semibold">Transfer custody</h2><div className="rounded-md border border-sky-200 bg-sky-50 p-3 text-sm text-sky-950">Internal-source intake must use the existing transfer workflow. Custody evidence carries only operational health, quarantine, treatment, licence, and safety facts; private research notes never travel.</div><div className="grid gap-4 xl:grid-cols-2">{workspace.options.transfers.map((transfer) => { const events = workspace.custodyEvents.filter((event) => event.requestId === transfer.id); const dispatched = events.some((event) => event.eventType === "dispatched"); const terminal = events.some((event) => ["dispatch_cancelled", "destination_received", "partial_failure"].includes(event.eventType)); const canSource = workspace.options.unitScoped || workspace.options.activeLabId === transfer.sourceLabId; const canDestination = workspace.options.unitScoped || workspace.options.activeLabId === transfer.destinationLabId; return <article className="space-y-3 rounded-lg border border-[var(--line)] bg-white p-4" key={transfer.id} data-testid="transfer-custody-card"><strong>Transfer {transfer.id.slice(-8)} · {transfer.status.replaceAll("_", " ")}</strong><p className="text-sm text-[var(--muted)]">{transfer.reason}</p>
        {canSource && transfer.status === "destination_accepted" && !dispatched ? <ActionForm action={dispatchTransferCustodyAction} commandKey={`${nonce}:dispatch:${transfer.id}:${transfer.version}`} submit="Record dispatch"><input name="transferRequestId" type="hidden" value={transfer.id} /><input name="expectedVersion" type="hidden" value={transfer.version} /><p className="text-xs text-[var(--muted)]">Uses the authoritative transfer version rendered with this packet.</p></ActionForm> : null}
        {canSource && dispatched && !terminal && transfer.status !== "finalized" ? <ActionForm action={cancelTransferDispatchAction} commandKey={`${nonce}:dispatch-cancel:${transfer.id}:${transfer.version}`} submit="Cancel dispatch"><input name="transferRequestId" type="hidden" value={transfer.id} /><input name="expectedVersion" type="hidden" value={transfer.version} /><Input name="reason" label="Cancellation reason" defaultValue="Synthetic custody dispatch cancelled before finalization." /></ActionForm> : null}
        {canDestination && dispatched && !terminal && transfer.status === "finalized" ? <ActionForm action={receiveTransferCustodyAction} commandKey={`${nonce}:receive:${transfer.id}:${transfer.version}`} submit="Confirm destination receipt"><input name="transferRequestId" type="hidden" value={transfer.id} /><input name="expectedVersion" type="hidden" value={transfer.version} /><div className="grid gap-2 sm:grid-cols-2"><Input name="healthStatus" label="Operational health status" defaultValue="Synthetic compatible packet reviewed" /><Input name="quarantineStatus" label="Quarantine status" defaultValue="Synthetic destination quarantine required" /><Input name="licenceStatus" label="Licence status" defaultValue="Synthetic authorization checked" /><Input name="safetyStatus" label="Safety status" defaultValue="Synthetic safety packet checked" /></div>{transfer.items.map((item) => <div className="grid gap-2 rounded border p-3 sm:grid-cols-2" key={item.animalId}><input name="animalId" type="hidden" value={item.animalId} /><input name="expectedIdentifier" type="hidden" value={item.animal.facilityAnimalId} /><p className="text-sm font-medium sm:col-span-2">{item.animal.facilityAnimalId}</p><Input name="observedIdentifier" label="Observed identifier" defaultValue={item.animal.facilityAnimalId} /><Select name="outcome" label="Outcome" options={[{ id: "received", label: "Received" }, { id: "missing", label: "Missing" }, { id: "mismatched", label: "Mismatched" }, { id: "damaged", label: "Damaged" }, { id: "dead_on_arrival", label: "Dead on arrival" }]} /><Input name="operationalCondition" label="Exception details (required unless received)" required={false} /></div>)}</ActionForm> : null}
        <div className="space-y-1 text-xs text-[var(--muted)]">{events.map((event) => <p key={event.id}>{event.eventType.replaceAll("_", " ")} · {event.observedItemCount}/{event.expectedItemCount} observed</p>)}</div>
      </article>; })}</div>
      <div className="grid gap-3 xl:grid-cols-2">{workspace.custodyReconciliations.map((row) => <article className="space-y-2 rounded-lg border border-[var(--line)] bg-white p-4" key={row.id} data-testid="custody-reconciliation"><strong>Custody discrepancy · {row.status.replaceAll("_", " ")}</strong>{workspace.permissions.canManage && row.status === "open" ? <ActionForm action={resolveTransferCustodyReconciliationAction} commandKey={`${nonce}:custody-resolve:${row.id}:${row.version}`} submit="Resolve custody discrepancy"><input name="reconciliationId" type="hidden" value={row.id} /><input name="expectedVersion" type="hidden" value={row.version} /><input name="action" type="hidden" value="resolve" /><Input name="reason" label="Resolution evidence" defaultValue="Synthetic custody discrepancy investigated." /></ActionForm> : null}{workspace.permissions.canApprove && row.status === "resolved" ? <ActionForm action={resolveTransferCustodyReconciliationAction} commandKey={`${nonce}:custody-signoff:${row.id}:${row.version}`} submit="Independently sign off"><input name="reconciliationId" type="hidden" value={row.id} /><input name="expectedVersion" type="hidden" value={row.version} /><input name="action" type="hidden" value="sign_off" /><Input name="reason" label="Sign-off reason" defaultValue="Independent synthetic custody sign-off." /></ActionForm> : null}</article>)}</div>
    </section> : null}
  </div>;
}
